"""Render the P5 pilot: ten vote summaries for human review.

Charter P5: "Pilot 10 samples into docs/reviews/ for human review; no
LLM-assisted text to production until approved."

Nothing here writes to the database or to any public surface. It reads votes,
renders the deterministic template, runs the figure gate, and writes markdown.

Samples are chosen by shape rather than at random: the cases that break a
template are the lopsided tally, the unanimous one, the vote with no published
results, the missing stage, the truncated title, and the teens that Lithuanian
numeral agreement gets wrong. A random ten would be ten ordinary votes.

Usage:
    DB_DSN=... .venv/bin/python -m scripts.pilot_vote_summaries
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import psycopg2
from psycopg2.extras import RealDictCursor

from pipeline.summaries import render_vote_summary, verify

COLUMNS = """
    seimas_vote_id, sitting_date, title, vote_type, project_id,
    votes_for, votes_against, votes_abstained, votes_participated, seats_eligible
"""

# (heading, why this shape is worth reviewing, SQL predicate + ordering)
SHAPES: tuple[tuple[str, str, str], ...] = (
    (
        "Įprastas balsavimas",
        "The ordinary case: a stage, a project number, a clear tally.",
        "votes_participated > 0 AND vote_type = 'Priėmimas' AND project_id IS NOT NULL"
        " ORDER BY voted_at DESC",
    ),
    (
        "Beveik vieningas",
        "A lopsided tally is where a template is most tempted to conclude that the"
        " question passed. It must not.",
        "votes_participated > 20 AND votes_against = 0 AND votes_abstained = 0"
        " ORDER BY votes_for DESC",
    ),
    (
        "Atmestas pagal skaičius, bet rezultato neskelbiame",
        "More against than for. The reader will supply „atmesta“ unless told the"
        " record does not say so.",
        "votes_participated > 20 AND votes_against > votes_for ORDER BY votes_against DESC",
    ),
    (
        "Nepaskelbti rezultatai",
        "1,656 of 5,286 votes. Must state the absence, never zeros.",
        "votes_participated = 0 ORDER BY voted_at DESC",
    ),
    (
        "Nenurodyta stadija",
        "vote_type is NULL on 252 rows. The stage must be named as unknown, not guessed.",
        "vote_type IS NULL AND votes_participated > 0 ORDER BY voted_at DESC",
    ),
    (
        "Šaltinio nukirstas pavadinimas",
        "571 titles stop at the source's 200-character cap. Quoting one as complete"
        " states something the record does not.",
        "length(title) = 200 AND rtrim(title) NOT LIKE '%)' AND votes_participated > 0"
        " ORDER BY voted_at DESC",
    ),
    (
        "Nukirstas pavadinimas su tarpais gale",
        "154 of those reach the cap only by counting trailing spaces. Measuring"
        " after strip() reports them as complete.",
        "length(title) = 200 AND length(rtrim(title)) < 200 AND rtrim(title) NOT LIKE '%)'"
        " ORDER BY voted_at DESC",
    ),
    (
        "Paribio skaitvardžiai (11–19)",
        "The teens take the genitive plural despite ending in 1. „11 narys“ reads"
        " as machine-generated text.",
        "votes_abstained BETWEEN 11 AND 19 AND votes_participated > 0 ORDER BY voted_at DESC",
    ),
    (
        "Vienas narys",
        "Singular agreement: „1 narys“, not „1 nariai“.",
        "votes_against = 1 AND votes_participated > 0 ORDER BY voted_at DESC",
    ),
    (
        "Klausimų grupė",
        "A synthesised title, not source text — the one title shape we compose"
        " ourselves, and the only one that exceeds 200 characters.",
        "title LIKE 'Klausimų grupė%' AND votes_participated > 0 ORDER BY voted_at DESC",
    ),
)


def fetch(cur, predicate: str):
    cur.execute(f"SELECT {COLUMNS} FROM votes WHERE {predicate} LIMIT 1")
    return cur.fetchone()


def main() -> int:
    dsn = os.environ.get("DB_DSN")
    if not dsn:
        print("DB_DSN is not set", file=sys.stderr)
        return 2

    out = Path(__file__).resolve().parents[1].parent / "docs" / "reviews" / "p5-vote-summary-pilot.md"
    conn = psycopg2.connect(dsn)
    cur = conn.cursor(cursor_factory=RealDictCursor)

    lines: list[str] = [
        "# P5 pilot — plain-language vote summaries",
        "",
        "Generated by `Seimas.v2/scripts/pilot_vote_summaries.py`. Read-only:",
        "nothing here has been written to the database or to any public surface.",
        "",
        "**What needs a human.** Every summary below is *working copy* under",
        "charter §2 — the Lithuanian needs a native reader. Two things need more",
        "than proofreading:",
        "",
        "1. The **stage glosses** („pateikimo stadijoje sprendžiama, ar apskritai",
        "   pradėti svarstyti projektą“ and its siblings) are claims about Seimas",
        "   procedure, not about our data. They need checking against the Statute.",
        "2. The sentence refusing to state an outcome appears on every summary. It",
        "   is the load-bearing one: `votes.result_type` is NULL on all 5,286 rows",
        "   because the source publishes no pass/fail field, and a reader looking",
        "   at 98–3 will supply „priimta“ unless told otherwise.",
        "",
        "**The figure gate.** Each sample is checked back against its database row:",
        "every digit in the text must trace to a named column, or to the verbatim",
        "quoted title. `pažeidimų: 0` below means the check passed. The gate exists",
        "for the step after this one — if an LLM is ever allowed to rephrase these,",
        "it runs on the rephrased string and rejects invented or dropped numbers.",
        "",
    ]

    total_violations = 0
    for i, (heading, why, predicate) in enumerate(SHAPES, start=1):
        row = fetch(cur, predicate)
        lines.append(f"## {i}. {heading}")
        lines.append("")
        lines.append(f"*{why}*")
        lines.append("")
        if row is None:
            lines.append("No vote in the database has this shape.")
            lines.append("")
            continue

        summary = render_vote_summary(row)
        violations = verify(summary, row)
        total_violations += len(violations)

        lines.append("> " + summary.text.replace("\n", " "))
        lines.append("")
        lines.append(
            f"`balsavimo_id {row['seimas_vote_id']}` · {row['sitting_date']} · "
            f"stadija: {row['vote_type'] or '—'} · projektas: {row['project_id'] or '—'}"
        )
        lines.append("")
        figures = ", ".join(f"`{f}`={v}" for f, v in summary.figures())
        lines.append(f"Figures checked: {figures}")
        lines.append("")
        if violations:
            lines.append("**PAŽEIDIMAI:**")
            for v in violations:
                lines.append(f"- `{v.kind}` — {v.detail}")
        else:
            lines.append("pažeidimų: 0")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"Total gate violations across the pilot: **{total_violations}**.")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} ({len(SHAPES)} samples, {total_violations} violations)")
    return 1 if total_violations else 0


if __name__ == "__main__":
    raise SystemExit(main())
