import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import {
  dashboardStatsSchema,
  factionAlignmentSchema,
  mpActivitySchema,
  mpDiarySchema,
  mpProfileSchema,
  mpSummaryListSchema,
  voteDetailSchema,
} from './api';

/**
 * The schema must accept every null the backend is allowed to send.
 *
 * This is the test that would have caught both blank-page defects. Twice in one
 * session a backend value was widened to null while the zod schema still
 * required a number: first `mp.party`, then
 * `forensic_breakdown.loyalty_bonus.independent_voting_days_pct`. The parse
 * failed, and because the profile page parses the whole payload at once, one
 * legitimately-absent value took every other field down with it — for 9
 * members, since the Speaker and all 8 former members sit in no faction.
 *
 * The existing contract test in provenanceContract.test.ts goes through
 * `parse` correctly but builds its payload by hand, and nobody hand-writes the
 * awkward case. So this file works from two sources of truth that are not
 * anyone's imagination:
 *
 *   - contracts/wire-nullability.json — every path the backend may null,
 *     declared once and also checked from the Python side.
 *   - contracts/fixtures/*.json — real payloads captured from production for
 *     members chosen by awkward property rather than by name.
 *
 * Failure here means the schema and the backend disagree about what is
 * optional. Fix the schema, not this test.
 */
const ROOT = join(__dirname, '..', '..', '..', 'contracts');

type Contract = {
  endpoints: Record<string, { nullable_paths: Record<string, string> }>;
};

const contract: Contract = JSON.parse(
  readFileSync(join(ROOT, 'wire-nullability.json'), 'utf-8'),
);
const nullablePaths = Object.keys(contract.endpoints.heroes_profile.nullable_paths);

const all = readdirSync(join(ROOT, 'fixtures'))
  .filter((f) => f.endsWith('.json'))
  .map((f) => ({
    name: f,
    ...JSON.parse(readFileSync(join(ROOT, 'fixtures', f), 'utf-8')),
  }));

/** Fixtures for the profile endpoint — real captures plus its degraded build. */
const fixtures = all.filter((f) => f.name.startsWith('heroes-'));

type CheckableSchema = {
  safeParse: (v: unknown) => { success: boolean; error?: unknown };
  parse: (v: unknown) => unknown;
};

const SCHEMAS: Record<string, CheckableSchema> = {
  mpProfileSchema,
  mpActivitySchema,
  mpDiarySchema,
  factionAlignmentSchema,
  // The v1 endpoints, which had no runtime schema at all until 2026-09-05.
  dashboardStatsSchema,
  mpSummaryListSchema,
  voteDetailSchema,
};

/**
 * Payloads built by handing the real route a database that finds nothing —
 * a fresh database, a failed backfill, an unrefreshed materialized view.
 * Generated by tests/test_degraded_payload.py, so they need no network and
 * cannot go stale. Each names the schema that must be able to read it.
 *
 * If a schema cannot parse its degraded payload, one empty table blanks that
 * surface for every visitor, with the suites green. That is not hypothetical:
 * it is how mp.active, mp.photo and press_releases were found.
 */
const degraded = all.filter((f) => typeof f.schema === 'string');

/**
 * Keys the backend sends that this client declines to declare, on purpose.
 *
 * Listing them here rather than declaring them keeps the drop deliberate and
 * reviewable: anything dropped that is NOT on this list fails the guard below.
 * Each entry is a descriptive count no surface renders today — none is a score,
 * a rank, or a label. If a surface starts needing one, declare it in the schema
 * and delete the line; the list should only ever shrink.
 */
const DELIBERATELY_UNDECLARED = new Set([
  // Ingest bookkeeping, not a fact about the member.
  '.mp.last_synced_at',
  // Bill and amendment counts. `legislation` holds 0 rows and these are fed
  // from a shadow source (P4 recon), so nothing displays them until the
  // canonical source question is settled — declaring them would invite a
  // surface to render a figure whose provenance is still open.
  '.metrics.bills_passed',
  '.metrics.bills_proposed',
  '.metrics.amendments_proposed',
  '.metrics.amendments_proposed_proxy',
]);

function setPath(obj: unknown, path: string, value: unknown): unknown {
  const clone = structuredClone(obj) as Record<string, unknown>;
  const parts = path.split('.');
  let cur: Record<string, unknown> = clone;
  for (const part of parts.slice(0, -1)) {
    if (cur[part] == null || typeof cur[part] !== 'object') return clone;
    cur = cur[part] as Record<string, unknown>;
  }
  cur[parts[parts.length - 1]] = value;
  return clone;
}

describe('the wire contract', () => {
  it('has fixtures and declared paths to check', () => {
    // Both lists empty would make every test below pass while checking nothing.
    expect(fixtures.length).toBeGreaterThan(0);
    expect(nullablePaths.length).toBeGreaterThan(0);
  });

  it.each(fixtures.map((f) => [f.name, f] as const))(
    'parses the real payload %s',
    (_name, fixture) => {
      const parsed = mpProfileSchema.safeParse(fixture.payload);
      if (!parsed.success) {
        throw new Error(
          `Captured payload for ${fixture._captured_mp} (${fixture._why}) does ` +
            `not parse. The backend and the schema disagree:\n` +
            JSON.stringify(parsed.error.issues, null, 2),
        );
      }
    },
  );

  it('has a degraded payload for every validated endpoint', () => {
    // A deleted fixture would make the checks below vacuously pass.
    const schemas = new Set(degraded.map((d) => d.schema));
    expect(schemas).toEqual(
      new Set([
        'mpProfileSchema',
        'mpActivitySchema',
        'mpDiarySchema',
        'factionAlignmentSchema',
        'dashboardStatsSchema',
        'mpSummaryListSchema',
        'voteDetailSchema',
      ]),
    );
  });

  it.each(degraded.map((d) => [d.name, d] as const))(
    'parses the degraded payload %s',
    (_name, fixture) => {
      const schema = SCHEMAS[fixture.schema as string];
      expect(schema, `unknown schema ${fixture.schema}`).toBeDefined();
      const parsed = schema.safeParse(fixture.payload);
      if (!parsed.success) {
        throw new Error(
          `${fixture.schema} cannot read a payload from an empty database. ` +
            `One empty table blanks this surface for everyone:\n` +
            JSON.stringify((parsed.error as { issues?: unknown }).issues, null, 2),
        );
      }
    },
  );

  it.each(degraded.map((d) => [d.name, d] as const))(
    'strips no key the backend sent from %s',
    (_name, fixture) => {
      // The one failure a successful parse cannot report. z.object() drops
      // undeclared keys silently, so a field the backend adds — or one nobody
      // thought to declare — vanishes between the wire and the render with
      // every test green. That is how metrics_provenance was emptied and three
      // dials disappeared in production.
      //
      // The first run of this guard found eleven dropped keys on the profile,
      // six of which were verdict-shaped — risk_score, high_risk_alerts,
      // forensic_penalties, social_bonus and two penalty sums, live on a public
      // payload about every named member. Those are gone from the backend now
      // (hero_engine.public_metrics), which is why they are not in the list
      // below. Everything that remains is a descriptive figure this client has
      // simply never rendered.
      const schema = SCHEMAS[fixture.schema as string];
      const dropped = (sent: unknown, got: unknown, path = ''): string[] => {
        if (Array.isArray(sent)) {
          return Array.isArray(got) && sent.length && got.length
            ? dropped(sent[0], got[0], `${path}[]`)
            : [];
        }
        if (sent === null || typeof sent !== 'object') return [];
        const g = (got ?? {}) as Record<string, unknown>;
        return Object.keys(sent as Record<string, unknown>).flatMap((k) =>
          k in g
            ? dropped((sent as Record<string, unknown>)[k], g[k], `${path}.${k}`)
            : [`${path}.${k}`],
        );
      };
      const missing = dropped(fixture.payload, schema.parse(fixture.payload)).filter(
        (p) => !DELIBERATELY_UNDECLARED.has(p),
      );
      expect(
        missing,
        `${fixture.schema} silently dropped ${missing.join(', ')} — the backend ` +
          `sends these and the surface will never see them`,
      ).toEqual([]);
    },
  );

  it.each(nullablePaths)('accepts null at %s', (path) => {
    // Applied to every fixture, not just one: a path can be nested under an
    // object that is itself absent in some payloads.
    for (const fixture of fixtures) {
      const mutated = setPath(fixture.payload, path, null);
      const parsed = mpProfileSchema.safeParse(mutated);
      if (!parsed.success) {
        throw new Error(
          `The backend is allowed to send null at "${path}" ` +
            `(${contract.endpoints.heroes_profile.nullable_paths[path]}) but the ` +
            `schema rejects it. This blanks the whole profile page, not just ` +
            `this field.\n${JSON.stringify(parsed.error.issues, null, 2)}`,
        );
      }
    }
  });
});
