"""Rewrite the degraded golden files. Run after an intended shape change."""
import json

from tests.test_degraded_payload import CASES, golden


def main() -> int:
    for stem, schema, build in CASES:
        path = golden(stem)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(
                {
                    "_why": "Generated by tests/test_degraded_payload.py from a "
                            "database that finds nothing. No DB or network, so it "
                            "cannot go stale.",
                    "schema": schema,
                    "payload": build(),
                },
                ensure_ascii=False,
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        print(f"  wrote {path.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
