#!/usr/bin/env python3
"""Measure the „Jaukumas“ palette against WCAG 2.2 and print the report.

Reads the tokens out of src/index.css and src/utils/partyColors.ts rather than
carrying a copy of them, so the report cannot drift from the palette. Run from
the dashboard directory:

    python3 scripts/contrast-report.py > ../../docs/reviews/jaukumas-contrast.md
"""
import colorsys
import datetime
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSS = (ROOT / "src/index.css").read_text()
PARTY_TS = (ROOT / "src/utils/partyColors.ts").read_text()


def _block(selector: str) -> str:
    i = CSS.index(selector + " {")
    return CSS[i:CSS.index("\n}", i)]


def _tokens(selector: str) -> dict[str, tuple[float, float, float]]:
    out = {}
    for m in re.finditer(r"--([a-z-]+):\s*([\d.]+)\s+([\d.]+)%\s+([\d.]+)%;", _block(selector)):
        h, s, l = float(m.group(2)), float(m.group(3)), float(m.group(4))
        r, g, b = colorsys.hls_to_rgb(h / 360, l / 100, s / 100)
        out[m.group(1)] = (r * 255, g * 255, b * 255)
    return out


LIGHT, DARK = _tokens(":root"), _tokens(".dark")


def _hex_to_rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _luminance(c) -> float:
    def channel(v):
        v /= 255
        return v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4
    r, g, b = c
    return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)


def ratio(a, b) -> float:
    la, lb = _luminance(a), _luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


# Every pair a reader actually sees, in both themes.
TEXT_PAIRS = [
    ("foreground", "background", 4.5, "Body text on page"),
    ("card-foreground", "card", 4.5, "Body text on card"),
    ("muted-foreground", "background", 4.5, "Secondary text on page"),
    ("muted-foreground", "card", 4.5, "Secondary text on card"),
    ("primary", "card", 4.5, "Pine link / „Už“ on card"),
    ("primary", "background", 4.5, "Pine link on page"),
    ("primary-foreground", "primary", 4.5, "Text on pine button"),
    ("destructive", "card", 4.5, "Clay „Prieš“ on card"),
    ("destructive", "background", 4.5, "Clay „Prieš“ on page"),
    ("vote-abstain", "card", 4.5, "Stone „Susilaikė“ on card"),
    ("attention-foreground", "attention", 4.5, "Ink on honey surface"),
    ("foreground", "muted", 4.5, "Text on muted panel"),
    ("sidebar-foreground", "sidebar", 4.5, "Sidebar nav text"),
    ("sidebar-accent-foreground", "sidebar-accent", 4.5, "Active sidebar item"),
]


def factions() -> list[tuple[str, str]]:
    seen, out = set(), []
    for short, hexv in re.findall(r"short:\s*'([^']+)',\s*hex:\s*'(#[0-9A-Fa-f]{6})'", PARTY_TS):
        if short in seen:
            continue
        seen.add(short)
        out.append((short, hexv))
    fallback = re.search(r"FALLBACK[^=]*=\s*\{\s*short:\s*'[^']*',\s*hex:\s*'(#[0-9A-Fa-f]{6})'", PARTY_TS)
    if fallback:
        out.append(("(fallback)", fallback.group(1)))
    return out


def main() -> None:
    ok_all = True
    print("# „Jaukumas“ contrast report")
    print()
    print("Generated by `Seimas.v2/dashboard/scripts/contrast-report.py`, which")
    print("reads the tokens out of `src/index.css` and `src/utils/partyColors.ts`")
    print("rather than carrying a copy of them. Re-run it after any palette")
    print("change:")
    print()
    print("```bash")
    print("cd Seimas.v2/dashboard && python3 scripts/contrast-report.py > ../../docs/reviews/jaukumas-contrast.md")
    print("```")
    print()
    print(f"Last run {datetime.date.today().isoformat()}, against WCAG 2.2:")
    print("**4.5:1** for normal text, **3:1** for large text (≥18.66px bold or")
    print("≥24px) and for non-text elements that carry meaning.")
    print()
    print("## Text pairs")
    print()
    print("| Pair | Light | Dark | Required | Verdict |")
    print("| --- | ---: | ---: | ---: | --- |")
    for fg, bg, need, label in TEXT_PAIRS:
        l, d = ratio(LIGHT[fg], LIGHT[bg]), ratio(DARK[fg], DARK[bg])
        ok = l >= need and d >= need
        ok_all &= ok
        print(f"| {label} | {l:.2f} | {d:.2f} | {need} | {'✅ AA' if ok else '❌ FAIL'} |")
    print()
    print("## Faction colours (non-text, 3:1)")
    print()
    print("The dot is the only thing distinguishing one faction from another in")
    print("a list, so it carries meaning and 3:1 applies. Measured against the")
    print("page background in both themes — the page is the harder case, being")
    print("slightly darker than the card.")
    print()
    print("| Faction | Hex | vs linen | vs charcoal | Verdict |")
    print("| --- | --- | ---: | ---: | --- |")
    worst = (99.0, "")
    for name, hexv in factions():
        c = _hex_to_rgb(hexv)
        l, d = ratio(c, LIGHT["background"]), ratio(c, DARK["background"])
        ok = l >= 3 and d >= 3
        ok_all &= ok
        if min(l, d) < worst[0]:
            worst = (min(l, d), name)
        print(f"| {name} | `{hexv}` | {l:.2f} | {d:.2f} | {'✅' if ok else '❌ FAIL'} |")
    print()
    print(f"Tightest margin: **{worst[1]}** at {worst[0]:.2f}:1.")
    print()
    print("## Deliberate exclusions")
    print()
    print("**Honey (`--attention`) is a surface, never a text colour.** `#C99A4B`")
    print("reaches 2.48:1 as text on the linen card, and darkening it far enough")
    print("to pass stops it being honey. It is used as a background with")
    print("`--attention-foreground` (ink) on top, which measures")
    print(f"{ratio(LIGHT['attention-foreground'], LIGHT['attention']):.2f}:1 light and "
          f"{ratio(DARK['attention-foreground'], DARK['attention']):.2f}:1 dark.")
    print()
    print("**White on faction colours stays.** Party badges and seat-map chips")
    print("set `text-white` over the faction hex. Those are chips, not body")
    print("text, and the faction palette is dark enough to carry white at badge")
    print("weight.")
    print()
    print("## What was changed to get here")
    print()
    print("Five values failed measurement and were changed rather than waived:")
    print()
    print("| Token | Was | Measured | Now |")
    print("| --- | --- | ---: | --- |")
    print("| Terracotta (Nemuno aušra) | `#C97B4A` | 2.79 | `#B66F3D` |")
    print("| Sage (Vardan LT) | `#7FA98C` | 2.96 | `#5D8A6C` |")
    print("| Plum (LRLS) | `#9A86B0` | 2.98 | `#937DAA` |")
    print("| Moss (LVŽS) | `#7A9B6E` | 2.84 | `#6E8E62` |")
    print("| Clay (`--destructive`) | `#B26A50` | 4.00 | `#A15F47` |")
    print()
    print("Two of these are worth naming. Plum and moss were signed off earlier")
    print("at 3.01:1 — measured against the **card**. Against the page they are")
    print("2.98 and 2.84, and a faction dot appears on both. The harder surface")
    print("is the one that governs.")
    print()
    print("Clay is the same shape of mistake. At `#B26A50` it passed the")
    print("large-text threshold and was accepted on that basis — but it is used")
    print("for 13px vote tallies in `DataStripVote`, where 3:1 does not apply.")
    print()
    print(f"**All pairs pass: {ok_all}**")


if __name__ == "__main__":
    main()
