import { describe, expect, it } from "vitest";
import { mkdtempSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

/**
 * The verdict guards scanned source files. A „Gėdos siena" — fifteen named
 * members ranked #1 to #15 with a euro figure for salary they had supposedly
 * not earned — lived in public/data/absenteeism.json, was fetched directly by a
 * component, and survived the heroes-villains retirement, the integrity-index
 * demotion and the loyalty de-ranking, because no grep over read paths ever
 * looked at a static asset.
 *
 * Anything shipped from public/ reaches a reader exactly as an API response
 * does. This asserts the shape, not the instance.
 *
 * A second instance of this same failure mode was found and removed
 * 2026-09-06: `public/wikis/index.json` labelled five named members
 * `risk_level: High/Medium/Low`, generated by an unreviewed LLM wiki task and
 * git-tracked in the public repository since the first commit. This guard was
 * already running when that file existed and did not catch it — `risk_level`
 * matched none of the patterns below. The vocabulary is extended accordingly,
 * and the third test below no longer depends on a real file existing to prove
 * the matchers work, which is what let the gap go unnoticed: once the
 * offending file is removed, a file-count check alone cannot tell a guard
 * that is watching an empty, clean directory apart from one that was never
 * wired up to scan anything.
 */
const PUBLIC_DIR = join(__dirname, "..", "..", "public");

// Keys that only exist to rank or judge a named person.
const FORBIDDEN_KEYS = [
  /^rank$/i,
  /unearned/i,
  /^top\d+_/i,
  /shame/i,
  /score$/i,
  /grade$/i,
  /risk[_-]?level/i,
  /integrity[_-]?score/i,
];

// Titles that pass judgement rather than describing a measurement.
const FORBIDDEN_TEXT = [
  /gėdos siena/i,
  /wall of shame/i,
  /neuždirb/i,
  /reitingas/i,
  /risk level/i,
];

function jsonFiles(dir: string): string[] {
  let out: string[] = [];
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const entry of entries) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out = out.concat(jsonFiles(full));
    else if (entry.endsWith(".json")) out.push(full);
  }
  return out;
}

function collectKeys(value: unknown, acc: string[] = []): string[] {
  if (Array.isArray(value)) value.forEach((v) => collectKeys(v, acc));
  else if (value && typeof value === "object") {
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      acc.push(k);
      collectKeys(v, acc);
    }
  }
  return acc;
}

describe("static data shipped to readers carries no verdicts", () => {
  const files = jsonFiles(PUBLIC_DIR);

  it("has no ranking or judgement keys", () => {
    const offenders: string[] = [];
    for (const file of files) {
      const keys = collectKeys(JSON.parse(readFileSync(file, "utf-8")));
      for (const key of keys) {
        if (FORBIDDEN_KEYS.some((re) => re.test(key))) {
          offenders.push(`${file.split("/public/")[1]}: ${key}`);
        }
      }
    }
    expect(offenders, "a rank or judgement key reached public/").toEqual([]);
  });

  it("has no text passing judgement on people", () => {
    const offenders: string[] = [];
    for (const file of files) {
      const raw = readFileSync(file, "utf-8");
      for (const re of FORBIDDEN_TEXT) {
        if (re.test(raw)) offenders.push(`${file.split("/public/")[1]}: ${re}`);
      }
    }
    expect(offenders, "judgement text reached public/").toEqual([]);
  });

  it("the matchers themselves catch a synthetic offender, independent of what public/ currently holds", () => {
    // The previous version of this test asserted files.length > 0 — real files
    // under public/ had to exist for a pass to mean anything. That coupling is
    // exactly what let risk_level ship undetected: nobody re-examined whether
    // the FORBIDDEN_* vocabulary actually covered it, because the test was
    // green. public/ is empty now that the offending file is gone, which is
    // the correct end state, not a reason this guard should stop proving
    // itself. Feed the real matching functions a case shaped like the one that
    // shipped, without touching disk.
    const keys = collectKeys({ mp_id: "x", risk_level: "High" });
    const keyOffenders = keys.filter((k) => FORBIDDEN_KEYS.some((re) => re.test(k)));
    expect(keyOffenders, "the key matcher no longer catches risk_level").not.toEqual([]);

    const textOffenders = FORBIDDEN_TEXT.filter((re) =>
      re.test('{"summary": "Conclusion — Risk Level: High"}'),
    );
    expect(textOffenders, "the text matcher no longer catches a risk-level verdict").not.toEqual(
      [],
    );
  });

  it("the walk itself finds a real file (a broken path would hide files silently)", () => {
    // jsonFiles() swallows a missing directory via its try/catch, so a typo in
    // PUBLIC_DIR would report zero files and every test above would pass
    // vacuously — the exact failure mode this whole file is about, one layer
    // down. A throwaway temp directory proves the walk function itself works,
    // without touching node_modules or depending on any file this repo happens
    // to ship today.
    const dir = mkdtempSync(join(tmpdir(), "verdict-guard-selftest-"));
    try {
      writeFileSync(join(dir, "nested.json"), "{}");
      expect(jsonFiles(dir)).toEqual([join(dir, "nested.json")]);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
